# Generated by Django 5.2.7 on 2025-11-15 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_managers_alter_profile_email_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
            ],
        ),
    ]
