# Generated by Django 5.2.7 on 2025-11-18 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_avatar_profile_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_image',
            new_name='avatar',
        ),
    ]
