# Generated by Django 5.2.7 on 2025-11-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_profile_image_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='images/default_profile.png', upload_to='avatars/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
